### ISSUE TITLE
Render errors for Authpanel

### ISSUE THREAD

**Issue by mn22nw** [mn22nw/favovid#1]
I'm trying to add a component for authentication (basically the same component as the one from [reduxfirebasedemo](https://github.com/krawaller/reduxfirebasedemo) ) and I can't seem to figure out what's messing up the render.

_These are the most relevant files_
 [authpanel.js](https://github.com/mn22nw/favovid/blob/master/src/components/authpanel.js) 
 [login.js](https://github.com/mn22nw/favovid/blob/master/src/components/pages/login.js)

**These are the two warnings I get:**

"Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `Login` "

"Uncaught Error: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `Login`."

**Comment by fyrkant** [comment]
I suspect that it’s the `import {Authpanel} from '../authpanel';` in `Login.js` that’s the problem! Try `import Authpanel from '../authpanel';` instead.
